source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ASPickerView_Example', :exclusive => true do
  pod "ASPickerView", :path => "../"
end

target 'ASPickerView_Tests', :exclusive => true do
  pod "ASPickerView", :path => "../"
  pod 'Quick', '~> 0.3.1'
end
